import "~/styles/globals.css";

import { type Metadata } from "next";
import { DM_Sans, Space_Grotesk } from 'next/font/google';
import Providers from "./providers";
import NextTopLoader from 'nextjs-toploader';
import Navbar from "~/components/Navbar";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "GitAsk",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
}

const sans = DM_Sans({
  subsets: ['latin'],
  weight: ['500','800']
})

const grotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '700'],
});


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${grotesk.className} antialiased min-h-screen`}>
      <body>
        <Providers>
           <TRPCReactProvider>{children}</TRPCReactProvider>
           <NextTopLoader height={5} color="#38bdf8" showSpinner={false} easing="ease"/>
           <Navbar />
        </Providers>
      </body>
    </html>
  );
}
